# Generated by Django 3.1.4 on 2021-03-04 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='admin_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.fields.CharField, to='system.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='admin_details',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='send_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_box', models.CharField(max_length=100000)),
                ('link_box', models.CharField(max_length=1000)),
                ('file_upload', models.CharField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.courses')),
            ],
        ),
    ]
