# Generated by Django 3.1.4 on 2021-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210305_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
