# Generated by Django 3.1.4 on 2021-03-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_students_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_notification',
            name='file_upload',
        ),
    ]
